export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const RESET_SERVICE_FIELD = 'RESET_SERVICE_FIELD';
export const LOAD_SERVICE_DATA = 'LOAD_SERVICE_DATA';
export const SET_FILTER = 'SET_FILTER';
export const RESET_FILTER = 'RESET_FILTER';